'use server';

import { detectReportType } from '@/ai/flows/detect-report-type';
import { parseCreditCard, parseDepositAccount, type CreditData, type DepositData, ParsedCreditDataWithCategory } from '@/lib/parser';

export type ReplacementRule = {
    find: string;
    replace: string;
    deleteRow?: boolean;
};

export type CategoryRule = {
    keyword: string;
    category: string;
};

function applyReplacementRules(description: string, rules: ReplacementRule[]): { processedText: string, shouldDelete: boolean } {
    let processedText = description;
    let shouldDelete = false;

    for (const rule of rules) {
        if (rule.find && description.includes(rule.find)) {
            if (rule.deleteRow) {
                shouldDelete = true;
                break;
            }
            processedText = processedText.replace(new RegExp(rule.find, 'g'), rule.replace);
        }
    }
    return { processedText, shouldDelete };
}


function applyCategoryRules(description: string, postingDate: string, rules: CategoryRule[]): string {
    for (const rule of rules) {
        if (rule.keyword && description.includes(rule.keyword)) {
            return rule.category;
        }
    }
    // If no rules match, return a default or empty category
    return '未分類';
}

async function processSingleCreditEntry(entry: ParsedCreditDataWithCategory, replacementRules: ReplacementRule[], categoryRules: CategoryRule[]): Promise<CreditData | null> {
    const { processedText: description, shouldDelete } = applyReplacementRules(entry.description, replacementRules);
    
    if (shouldDelete || !description.trim()) {
        return null;
    }
    
    // If a category was parsed directly from the paste, use it. Otherwise, apply rules.
    const category = entry.category || applyCategoryRules(description, entry.postingDate, categoryRules);

    return {
        id: entry.id, // Use the ID generated by the parser
        transactionDate: entry.transactionDate,
        category: category,
        description: description,
        amount: entry.amount,
    };
}


export async function processBankStatement(
    text: string, 
    replacementRules: ReplacementRule[],
    categoryRules: CategoryRule[]
): Promise<{
    success: boolean;
    creditData: CreditData[];
    depositData: DepositData[];
    detectedCategories: string[];
    error?: string;
}> {
    if (!text || text.trim().length < 10) {
        return { success: false, creditData: [], depositData: [], detectedCategories: [], error: "No text provided or text is too short." };
    }

    try {
        const sections = text.split(/(?=交易日期)/).filter(s => s.trim() !== '');
        let allCreditData: CreditData[] = [];
        let allDepositData: DepositData[] = [];
        const detectedCategories = new Set<string>();

        for (const section of sections) {
            const { reportType } = await detectReportType({ text: section });

            if (reportType === 'credit_card') {
                const rawParsed = await parseCreditCard(section);
                rawParsed.forEach(c => { if(c.category) detectedCategories.add(c.category) });
                const processedPromises = rawParsed.map(entry => processSingleCreditEntry(entry, replacementRules, categoryRules));
                const processedEntries = (await Promise.all(processedPromises)).filter((e): e is CreditData => e !== null);
                allCreditData.push(...processedEntries);

            } else if (reportType === 'deposit_account') {
                const parsed = await parseDepositAccount(section, replacementRules, categoryRules);
                 parsed.forEach(d => detectedCategories.add(d.category));
                allDepositData.push(...parsed);
            } else { 
                // Fallback: try parsing as credit card first
                const rawParsed = await parseCreditCard(section);
                if (rawParsed.length > 0) {
                    rawParsed.forEach(c => { if(c.category) detectedCategories.add(c.category) });
                    const processedPromises = rawParsed.map(entry => processSingleCreditEntry(entry, replacementRules, categoryRules));
                    const processedEntries = (await Promise.all(processedPromises)).filter((e): e is CreditData => e !== null);
                    allCreditData.push(...processedEntries);
                } else {
                    // Then try as deposit account if credit parsing yields nothing
                    const depositParsed = await parseDepositAccount(section, replacementRules, categoryRules);
                     if (depositParsed.length > 0) {
                        depositParsed.forEach(d => detectedCategories.add(d.category));
                        allDepositData.push(...depositParsed);
                    }
                }
            }
        }
        
        return { success: true, creditData: allCreditData, depositData: allDepositData, detectedCategories: Array.from(detectedCategories) };
    } catch (e) {
        console.error("Error processing bank statement:", e);
        const error = e instanceof Error ? e.message : 'An unknown error occurred during parsing.';
        return { success: false, creditData: [], depositData: [], detectedCategories: [], error };
    }
}
