'use server';

import { parseCreditCard, parseDepositAccount, type CreditData, type DepositData, type CashData, ParsedCreditDataWithCategory, parseExcelData } from '@/lib/parser';

export type ReplacementRule = {
    find: string;
    replace: string;
    deleteRow?: boolean;
};

export type CategoryRule = {
    keyword: string;
    category: string;
};

function applyReplacementRules(description: string, rules: ReplacementRule[]): { processedText: string, shouldDelete: boolean } {
    let processedText = description;
    let shouldDelete = false;

    for (const rule of rules) {
        if (rule.find && description.includes(rule.find)) {
            if (rule.deleteRow) {
                shouldDelete = true;
                break;
            }
            processedText = processedText.replace(new RegExp(rule.find, 'g'), rule.replace);
        }
    }
    return { processedText, shouldDelete };
}


function applyCategoryRules(description: string, postingDate: string, rules: CategoryRule[]): string {
    for (const rule of rules) {
        if (rule.keyword && description.includes(rule.keyword)) {
            return rule.category;
        }
    }
    // If no rules match, return a default or empty category
    return '未分類';
}

async function processSingleCreditEntry(entry: ParsedCreditDataWithCategory, replacementRules: ReplacementRule[], categoryRules: CategoryRule[]): Promise<CreditData | null> {
    const { processedText: description, shouldDelete } = applyReplacementRules(entry.description, replacementRules);
    
    if (shouldDelete || !description.trim()) {
        return null;
    }
    
    // If a category was parsed directly from the paste, use it. Otherwise, apply rules.
    const category = entry.category || applyCategoryRules(description, entry.postingDate, categoryRules);

    return {
        id: entry.id, // Use the ID generated by the parser
        transactionDate: entry.transactionDate,
        category: category,
        description: description,
        amount: entry.amount,
        bankCode: (entry as any).bankCode // Keep bank code if parser found it
    };
}


export async function processBankStatement(
    text: string, 
    replacementRules: ReplacementRule[],
    categoryRules: CategoryRule[],
    isExcelUpload: boolean = false,
    excelData?: any[][]
): Promise<{
    success: boolean;
    creditData: CreditData[];
    depositData: DepositData[];
    cashData: CashData[];
    detectedCategories: string[];
    error?: string;
}> {
    if (!text && !isExcelUpload) {
        return { success: false, creditData: [], depositData: [], cashData: [], detectedCategories: [], error: "No text provided." };
    }

    try {
        const detectedCategories = new Set<string>();
        let allCreditData: CreditData[] = [];
        let allDepositData: DepositData[] = [];
        let allCashData: CashData[] = [];

        if (isExcelUpload && excelData) {
            const parsedDataFromExcel = await parseExcelData(excelData);
            allCreditData = parsedDataFromExcel.creditData;
            allDepositData = parsedDataFromExcel.depositData;
            allCashData = parsedDataFromExcel.cashData;
            parsedDataFromExcel.detectedCategories.forEach(c => detectedCategories.add(c));
        } else {
             // Attempt to parse as credit card data
            const rawCreditParsedPromise = parseCreditCard(text);
            
            // Attempt to parse as deposit account data
            const depositParsedPromise = parseDepositAccount(text, replacementRules, categoryRules);

            const [rawCreditParsed, depositParsed] = await Promise.all([rawCreditParsedPromise, depositParsedPromise]);

            // Process credit card entries
            rawCreditParsed.forEach(c => { if(c.category) detectedCategories.add(c.category) });
            const processedCreditPromises = rawCreditParsed.map(entry => processSingleCreditEntry(entry, replacementRules, categoryRules));
            allCreditData = (await Promise.all(processedCreditPromises)).filter((e): e is CreditData => e !== null);

            // Process deposit account entries
            depositParsed.forEach(d => detectedCategories.add(d.category));
            allDepositData = depositParsed;
        }
        
        return { 
            success: true, 
            creditData: allCreditData, 
            depositData: allDepositData, 
            cashData: allCashData,
            detectedCategories: Array.from(detectedCategories) 
        };

    } catch (e) {
        console.error("Error processing bank statement:", e);
        const error = e instanceof Error ? e.message : 'An unknown error occurred during parsing.';
        return { success: false, creditData: [], depositData: [], cashData: [], detectedCategories: [], error };
    }
}
